//! Golden tests: the Rust ports of `chunk_text`, `markdown_to_html`, and the
//! delivery fallback classifiers must match the Python reference implementation
//! on these vectors. The private classifier tests live beside their implementation.
//!
//! Vectors are generated by `tests/golden/generate_vectors.py` (verbatim
//! copies of the console-chat-gpt functions). If you believe a vector is
//! wrong, regenerate it from the Python reference — never hand-edit the JSON.
//!
//! Implementer note: the reference indexes strings by
//! Unicode CODE POINTS, not bytes. `chunk_size` is a code-point count.

use serde::Deserialize;

#[derive(Deserialize)]
struct ChunkCase {
    name: String,
    input: String,
    chunk_size: usize,
    expected: Vec<String>,
}

#[derive(Deserialize)]
struct MarkdownCase {
    name: String,
    input: String,
    expected: String,
}

#[test]
fn chunk_text_matches_python_reference() {
    let cases: Vec<ChunkCase> =
        serde_json::from_str(include_str!("golden/chunk_text.json")).unwrap();
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in cases {
        let actual = tellm_telegram::chunk_text(&case.input, case.chunk_size);
        if actual != case.expected {
            failures.push(format!(
                "case {}: expected {:?}, got {:?}",
                case.name, case.expected, actual
            ));
        }
    }
    assert!(failures.is_empty(), "\n{}", failures.join("\n"));
}

#[test]
fn markdown_to_html_matches_python_reference() {
    let cases: Vec<MarkdownCase> =
        serde_json::from_str(include_str!("golden/markdown_to_html.json")).unwrap();
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in cases {
        let actual = tellm_telegram::markdown_to_html(&case.input);
        if actual != case.expected {
            failures.push(format!(
                "case {}: expected {:?}, got {:?}",
                case.name, case.expected, actual
            ));
        }
    }
    assert!(failures.is_empty(), "\n{}", failures.join("\n"));
}

/// Not ignored: guards the vector files themselves against accidental
/// corruption (hand-edits, bad merges).
#[test]
fn golden_vectors_parse_and_are_nonempty() {
    let chunks: Vec<ChunkCase> =
        serde_json::from_str(include_str!("golden/chunk_text.json")).unwrap();
    let markdown: Vec<MarkdownCase> =
        serde_json::from_str(include_str!("golden/markdown_to_html.json")).unwrap();
    let fallback: Vec<serde_json::Value> =
        serde_json::from_str(include_str!("golden/fallback_classification.json")).unwrap();
    assert!(chunks.len() >= 15, "chunk vectors missing");
    assert!(markdown.len() >= 20, "markdown vectors missing");
    assert!(fallback.len() >= 20, "fallback vectors missing");
    // Every case must be named and chunk expectations must reassemble to the input.
    for case in &chunks {
        assert!(!case.name.is_empty());
        assert_eq!(
            case.expected.concat(),
            case.input,
            "chunks must reassemble losslessly: {}",
            case.name
        );
        assert!(case.chunk_size > 0);
    }
    for case in &markdown {
        assert!(!case.name.is_empty());
    }
    for case in &fallback {
        assert!(case.get("name").and_then(|value| value.as_str()).is_some());
        assert!(matches!(
            case.get("classifier").and_then(|value| value.as_str()),
            Some("rich" | "html")
        ));
        assert!(case.get("input").and_then(|value| value.as_str()).is_some());
        assert!(
            case.get("expected")
                .and_then(|value| value.as_bool())
                .is_some()
        );
    }
}
